import Link from 'next/link';
import WorkGrid from '@/components/work-grid';

export default function Home() {
  return <>
    <header className="site-header"><Link className="wordmark" href="/" aria-label="Bart Consedine home">bc<span>↗</span></Link><nav aria-label="Main navigation"><a href="#about">About</a><a href="#work">Selected work</a><a className="nav-contact" href="#contact">Let’s connect <span aria-hidden="true">↗</span></a></nav></header>
    <main id="main">
      <section className="hero wrap" aria-labelledby="intro-title"><div className="hero-copy"><p className="eyebrow"><span className="small-dot"/> ENGINEER · MARKETER · ENTREPRENEUR</p><h1 id="intro-title">Software,<br/>growth &amp; the<br/><em>space between.</em></h1><p className="hero-intro">I’m Bart Consedine. I build digital products with an engineer’s curiosity and a marketer’s perspective.</p><a className="button dark" href="#work">Explore my work <span aria-hidden="true">↘</span></a><a className="hero-text-link" href="#about">A little about me <span aria-hidden="true">↓</span></a></div><div className="portrait-wrap"><div className="portrait-frame"><img src="/images/headshot.jpeg" alt="Bart Consedine" width="700" height="700" fetchPriority="high"/><span className="portrait-name">BART CONSEDINE</span></div><span className="portrait-note">A little technical.<br/>A little entrepreneurial.<br/><em>Always curious.</em></span><span className="orbit-mark" aria-hidden="true">✳</span></div></section>
      <div className="experience-strip"><div className="wrap"><p>EXPERIENCE ACROSS</p><span>SpringServe</span><span>Parsec Media</span><span>QuiBids</span><span>SocialFly</span></div></div>
      <section id="about" className="about wrap"><div><p className="eyebrow">01 / A LITTLE CONTEXT</p><h2>Different disciplines.<br/><em>One curious mind.</em></h2></div><div className="about-story"><p className="lead">My career connects digital advertising, software engineering, and business strategy. The common thread is curiosity about how things can work better.</p><p>I started in digital advertising and entrepreneurship, including co-founding QuiBids, before moving into software engineering. After an MBA, I worked in technical due diligence with EY-Parthenon Software Strategy Group.</p><p>At Magnite, my path has included serving as Chief of Staff to the CTO and leading engineering AI initiatives. I’m drawn to work that brings technology, strategy, and people together.</p><a className="inline-link" href="https://www.linkedin.com/in/bartconsedine">More on LinkedIn <span aria-hidden="true">↗</span></a></div></section>
      <section id="work" className="work-section wrap"><div className="section-heading"><div><p className="eyebrow">02 / SELECTED WORK</p><h2>From the product<br/><em>to the bigger picture.</em></h2></div><p>A few highlights from a career at the intersection of technology and growth.</p></div><WorkGrid/></section>
      <section className="toolkit wrap"><p className="eyebrow">03 / HOW I WORK</p><div className="toolkit-grid"><h2>Thinking across<br/><em>the whole stack.</em></h2><div><h3>Build</h3><p>JavaScript · React · Next.js<br/>Ruby on Rails · Python · SQL</p></div><div><h3>Grow</h3><p>Performance marketing<br/>Campaign &amp; landing page optimization</p></div><div><h3>Connect</h3><p>Data modeling · Reporting<br/>Creative · Client services</p></div></div></section>
      <section id="contact" className="contact"><div className="wrap"><p className="eyebrow">LET’S COMPARE NOTES</p><h2>Good things start<br/>with a <em>conversation.</em></h2><a className="button light" href="mailto:bartconsedine@gmail.com">Say hello <span aria-hidden="true">↗</span></a><a className="contact-link" href="https://www.linkedin.com/in/bartconsedine">LinkedIn ↗</a><span className="contact-star" aria-hidden="true">✳</span></div></section>
    </main><footer className="site-footer wrap"><span>© {new Date().getFullYear()} Bart Consedine</span><span>Built with curiosity.</span><Link href="/login">Private workspace <span aria-hidden="true">↗</span></Link></footer>
  </>;
}
