select jsonb_build_object(
  'tables', (select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'rls',c.relrowsecurity,'force',c.relforcerowsecurity) order by n.nspname,c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and c.relkind='r' and c.relname <> '_prisma_migrations'),
  'columns', (select jsonb_agg(jsonb_build_object('table',a.attrelid::regclass::text,'name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notnull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid)) order by a.attrelid::regclass::text,a.attnum) from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid in ('private.site_owner'::regclass,'public.app_data'::regclass) and a.attnum>0 and not a.attisdropped),
  'constraints', (select jsonb_agg(jsonb_build_object('table',conrelid::regclass::text,'name',conname,'definition',pg_get_constraintdef(oid)) order by conname) from pg_constraint where conrelid in ('private.site_owner'::regclass,'public.app_data'::regclass)),
  'policies', (select jsonb_agg(to_jsonb(p) order by schemaname,tablename,policyname) from pg_policies p where schemaname in ('public','private')),
  'functions', (select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'definer',p.prosecdef,'volatility',p.provolatile,'config',p.proconfig,'source',regexp_replace(p.prosrc,'\s','','g'),'anon',has_function_privilege('anon',p.oid,'EXECUTE'),'authenticated',has_function_privilege('authenticated',p.oid,'EXECUTE')) order by n.nspname,p.proname) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.proname in ('is_site_owner','is_site_admin')),
  'grants', (select jsonb_agg(jsonb_build_object('role',r,'table',t,'privilege',p,'allowed',has_table_privilege(r,t,p)) order by r,t,p) from unnest(array['anon','authenticated']) r cross join unnest(array['private.site_owner','public.app_data']) t cross join unnest(array['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER']) p),
  'private_usage', has_schema_privilege('authenticated','private','USAGE')
) as state;
